description: Arkansas counts the following deductions in itemized deduction.
values:
  2021-01-01:
    - ar_post_secondary_education_tuition_deduction
    - ar_medical_expense_deduction
    - ar_msc_deduction
    - real_estate_taxes
    - charitable_deduction
    - interest_deduction
    - casualty_loss_deduction
metadata:
  unit: list
  label: Arkansa itemized deduction sources
  reference:
    - title: Arkansas 2022 Individual Income Tax Forms and Instructions 
      href: https://www.dfa.arkansas.gov/images/uploads/incomeTaxOffice/2022_AR1000F_and_AR1000NR_Instructions.pdf#page=21
    - title: Arkansas 2021 Individual Income Tax Forms and Instructions 
      href: https://www.dfa.arkansas.gov/images/uploads/incomeTaxOffice/2021_AR1000F_and_AR1000NR_Instructions.pdf#page=21
