description: Arkansas counts the following deductions in itemized deduction.
values:
  2021-01-01:
    - ar_post_secondary_education_tuition_deduction
    - ar_medical_expense_deduction
    - ar_msc_deduction
    - real_estate_taxes
    - charitable_deduction
    - interest_deduction
    - casualty_loss_deduction
metadata:
  unit: list
  label: Arkansa itemized deductions
